name: Deploy Live Site to Firebase Hosting
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # This step installs the Firebase CLI and then calls it directly.
      # The --project flag tells it which project to use, and the
      # --only flag tells it which site within that project to deploy to.
      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --project galway-jam-circle-live --only hosting:galway-jam-circle-live

